### ISSUE TITLE
发现一个崩溃的bug

### ISSUE THREAD

**Issue by isweal** [qylibohao/BHInfiniteScrollView#1]
如果是以push的方式进入轮播的viewController
<img width="310" alt="2016-03-18 16 33 24" src="https://cloud.githubusercontent.com/assets/6571652/13872735/74135b44-ed27-11e5-822a-32797cf6f6a7.png">
再返回就会崩溃
<img width="970" alt="2016-03-18 16 34 04" src="https://cloud.githubusercontent.com/assets/6571652/13872817/11980dd8-ed28-11e5-81db-a5be22e1ff57.png">
这里获取的indexPath估计是错误的

**Comment by qylibohao** [comment]
已修复
